apiVersion: v1
kind: Pod
metadata:
  name: mult-container
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: 1st
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /user/share/nginx/html
    - name: 2nd
      image: debian
      ports:
        - containerPort: 81
      volumeMounts:
        - name: html
          mountPath: /html
      command: ['/bin/sh', '-c']
      args:
        - while true; do
          date >> /html/index.html;
          sleep 1;
          done
