apiVersion: apps/v1
kind: Deployment
metadata:
  name: dobby-replicas
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dobby-pod
  template:
    metadata:
      labels:
        app: dobby-pod
    spec:
      containers:
        - name: dobby
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444
