apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deploy
  namespace: svc-dns-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      name: test-app-pod
      labels:
        app: test-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
